# # remote_theme: pages-themes/primer@v0.2.0
# # plugins:
# # - jekyll-remote-theme # add this line to the plugins list if you already have one
# title: My Custom R Function
# description: A group of manual functions designed for EDA
# show_downloads: true
# markdown: kramdown
# kramdown:
#   input: GFM
#   math_engine: mathjax
  
  
title: My Custom R Function
description: A group of manual functions designed for EDA
show_downloads: true
theme: jekyll-theme-minimal  # Clean and simple
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax